# Generated by Django 5.2.8 on 2025-11-16 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=500, verbose_name='Диагноз (МКБ-10)')),
                ('status', models.CharField(choices=[('urgent', 'Срочно'), ('monitoring', 'Наблюдение'), ('stable', 'Стабильный')], default='monitoring', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание случая')),
                ('admission_date', models.DateField(verbose_name='Дата поступления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('doctors', models.ManyToManyField(related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='Врачи')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Консилиум',
                'verbose_name_plural': 'Консилиумы',
                'ordering': ['-admission_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='patients.case', verbose_name='Консилиум')),
            ],
            options={
                'verbose_name': 'Сообщение консилиума',
                'verbose_name_plural': 'Сообщения консилиумов',
                'ordering': ['created_at'],
            },
        ),
    ]
