# Generated by Django 5.2.8 on 2025-11-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_messagereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction',
            field=models.CharField(choices=[('👍', '👍'), ('👎', '👎')], max_length=2, verbose_name='Реакция'),
        ),
    ]
