# Generated by Django 5.2.8 on 2025-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Кардиолог', 'Кардиолог'), ('Невролог', 'Невролог'), ('Пульмонолог', 'Пульмонолог'), ('Анестезиолог-реаниматолог', 'Анестезиолог-реаниматолог'), ('Рентгенолог', 'Рентгенолог'), ('Гастроэнтеролог', 'Гастроэнтеролог'), ('Хирург', 'Хирург'), ('Нефролог', 'Нефролог'), ('Уролог', 'Уролог'), ('ЛОР', 'ЛОР')], max_length=100, null=True, verbose_name='Специализация'),
        ),
    ]
