# Generated by Django 5.2.8 on 2025-11-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='Ключ')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_keys', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_keys', to=settings.AUTH_USER_MODEL, verbose_name='Использован пользователем')),
            ],
            options={
                'verbose_name': 'Регистрационный ключ',
                'verbose_name_plural': 'Регистрационные ключи',
                'ordering': ['-created_at'],
            },
        ),
    ]
